# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a001aed67373f1a53fc509d7806ca5c82d268157930cb0059b2247a6defa3083d167317e620b664324cc570fa8c3f910bec6a15bf767bc47491190bdfdce491f

test:
  secret_key_base: 2d55dffb2d7544fa7bde8f4a178a0e3df7762a7fb2d23d4ffcae6bda6f7648de361ef2226cc348a7cdc45e61550c8fec72a98055269d369b971b6e390ead25c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
